spring.application.name=task-api

jwt.secret=${JWT_SECRET:+oeBA7bD+6kPZSf8jTzePkYO05GlzaRWpMn5tN+cLN8=}
jwt.expiration=86400000

spring.datasource.url=jdbc:h2:mem:mydb
spring.datasource.username=sa

springdoc.swagger-ui.path=/swagger-ui.html

#spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
#spring.datasource.username=postgres
#spring.datasource.password=postgres